kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv
  labels:
    pv: pgdata
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  hostPath:
    path: /mnt/db-data-posgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: app
          operator: In
          values:
          - openproject
  persistentVolumeReclaimPolicy: Retain
