kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv1
  labels:
    pv: opdata
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  hostPath:
    path: /mnt/opdata
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: app
          operator: In
          values:
          - openproject
  persistentVolumeReclaimPolicy: Retain
