kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv
  labels:
    pv: pgdata
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  hostPath:
    path: /mnt/db-data-posgres
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: app
            operator: In
            values:
            - openproject
  persistentVolumeReclaimPolicy: Retain
